### ISSUE TITLE
Typo in chapters/qa-10.mdx

### ISSUE THREAD

**Issue by AnthonyNet** [pegak/nauc-me-it#95]
Original:
Začneme jednodušším view modem, který **`složí`** jen k prohlížení.

Suggestion:
Začneme `s` jednodušším view modem, který **`slouží`** jen k prohlížení.

**Comment by pegak** [comment]
Klidně můžeš vytvořit PR, kde to fixneš. Potom stačí jen v commitu napsat `closes #95` a ono se to samo propojí. :) Případně se můžeš na Discordu spojit s @TSNheathen, který už podobnou věc dělal pro kapitoly 0 až 3. :)
